version: 0.0
os: linux
files:
  - source: /
    destination: /opt/redmine/
permissions:
  - object: /opt/redmine/
    owner: root
    group: root
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: update.sh
      timeout: 1000
      runas: root
