version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-codedeploy
permissions:
  - object: /home/ubuntu
    owner: root
    group: root
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: nginx.sh
      timeout: 300
      runas: root
